# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello_world.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hello_world.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\x12\x0bhello_world\"\x13\n\x11HelloWorldRequest\"%\n\x12HelloWorldResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2`\n\x11HelloWorldService\x12K\n\x08SayHello\x12\x1e.hello_world.HelloWorldRequest\x1a\x1f.hello_world.HelloWorldResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOWORLDREQUEST']._serialized_start=34
  _globals['_HELLOWORLDREQUEST']._serialized_end=53
  _globals['_HELLOWORLDRESPONSE']._serialized_start=55
  _globals['_HELLOWORLDRESPONSE']._serialized_end=92
  _globals['_HELLOWORLDSERVICE']._serialized_start=94
  _globals['_HELLOWORLDSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
